spring:
  application:
    name: JwtAuthService
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
security:
  jwt:
    key:
      private: ${PRIVATE_KEY}
    user:
      generator: ${JWT_USER_GENERATOR}
    expire: ${JWT_EXPIRE}